import type { AgeGroup, Quest } from '../types';

export const ALL_QUESTS: Quest[] = [
  // --- LEARNING (Reading) ---
  {
    id: 'read_1',
    type: 'reading',
    needType: 'learning',
    title: 'Прочитай вслух',
    description: 'Дракоша хочет послушать сказку! Прочитай текст вслух.',
    instruction: 'Нажми на микрофон и читай вслух — я буду слушать',
    xpReward: 30,
    readingText: 'Жила-была маленькая звёздочка по имени Лучик. Каждую ночь она светила над лесом и помогала животным находить дорогу домой. Все любили Лучика за её доброе сердце и яркий свет.',
  },
  {
    id: 'read_2',
    type: 'reading',
    needType: 'learning',
    title: 'История о дружбе',
    description: 'Дракоша скучает! Расскажи ему историю о дружбе.',
    instruction: 'Читай текст вслух, чётко и не спеша',
    xpReward: 30,
    readingText: 'Лис и Заяц жили в одном лесу. Однажды заяц попал в ловушку. Лис не побоялся и помог другу выбраться. С тех пор они стали лучшими друзьями и всегда помогали друг другу.',
  },
  {
    id: 'read_3',
    type: 'reading',
    needType: 'learning',
    title: 'Загадка природы',
    description: 'Узнай, как появляется радуга!',
    instruction: 'Прочитай текст вслух, как настоящий учёный',
    xpReward: 35,
    readingText: 'Радуга появляется, когда солнечный свет проходит через капельки воды в воздухе. Свет разделяется на семь цветов: красный, оранжевый, жёлтый, зелёный, голубой, синий и фиолетовый. Вот почему после дождя так красиво!',
  },
  {
    id: 'read_4',
    type: 'reading',
    needType: 'learning',
    title: 'Про космос',
    description: 'Дракоша любит звёзды! Расскажи ему о космосе.',
    instruction: 'Читай не спеша, делай паузы на запятых',
    xpReward: 35,
    readingText: 'Наша планета Земля вращается вокруг Солнца. Солнце — это огромная звезда, которая даёт нам тепло и свет. В нашей Солнечной системе восемь планет. Самая большая — Юпитер, а самая маленькая — Меркурий.',
  },
  {
    id: 'read_5',
    type: 'reading',
    needType: 'learning',
    title: 'Сказка о храбром рыцаре',
    description: 'Дракоша хочет услышать про приключения!',
    instruction: 'Читай выразительно, как артист!',
    xpReward: 40,
    readingText: 'В далёком королевстве жил храбрый рыцарь Даниил. Однажды злой дракон украл солнце и спрятал его в горе. Рыцарь не испугался и отправился в путь. Он решил задачку дракона, вернул солнце и сделал дракона своим другом.',
  },
  {
    id: 'read_6',
    type: 'story',
    needType: 'learning',
    ageGroups: ['9-11'],
    title: 'Придумай продолжение',
    description: 'Дракоша хочет узнать, что будет дальше в твоей истории!',
    instruction: 'Прочитай начало и продолжи историю своими словами вслух',
    xpReward: 45,
    readingText: 'Маша нашла в лесу волшебный сундук. Когда она открыла крышку, оттуда вылетела маленькая фея...',
  },
  {
    id: 'quiz_math_1',
    type: 'quiz',
    needType: 'learning',
    ageGroups: ['6-8'],
    title: 'Счёт звёзд',
    description: 'Посчитай, сколько звёзд осталось у Дракоши.',
    instruction: 'Выбери правильный ответ',
    xpReward: 35,
    quizQuestion: 'У Дракоши было 8 звёзд, 3 он подарил друзьям. Сколько звёзд осталось?',
    quizOptions: ['4', '5', '6', '7'],
    quizAnswerIndex: 1,
    quizHint: 'Подумай: 8 - 3 = ?',
  },
  {
    id: 'quiz_logic_1',
    type: 'quiz',
    needType: 'learning',
    ageGroups: ['6-8'],
    title: 'Лишний предмет',
    description: 'Найди лишний предмет в маленькой группе.',
    instruction: 'Подумай, что отличается от остальных',
    xpReward: 35,
    quizQuestion: 'Что лишнее: яблоко, груша, морковь, банан?',
    quizOptions: ['Яблоко', 'Груша', 'Морковь', 'Банан'],
    quizAnswerIndex: 2,
    quizHint: 'Три варианта — фрукты, а один — овощ.',
  },
  {
    id: 'quiz_math_2',
    type: 'quiz',
    needType: 'learning',
    ageGroups: ['9-11'],
    title: 'Кодовый расчёт',
    description: 'Дракоша открыл математический замок.',
    instruction: 'Сначала умножай, потом складывай',
    xpReward: 45,
    quizQuestion: 'Сколько получится: 6 + 4 × 2 ?',
    quizOptions: ['14', '16', '18', '20'],
    quizAnswerIndex: 0,
    quizHint: 'Сначала 4 × 2, потом прибавь 6.',
  },
  {
    id: 'quiz_logic_2',
    type: 'quiz',
    needType: 'learning',
    ageGroups: ['9-11'],
    title: 'Секретный порядок',
    description: 'Найди закономерность в ряду чисел.',
    instruction: 'Посмотри, что происходит с каждым числом',
    xpReward: 45,
    quizQuestion: 'Какое число будет следующим: 2, 4, 8, 16, ?',
    quizOptions: ['18', '20', '24', '32'],
    quizAnswerIndex: 3,
    quizHint: 'Каждое число удваивается.',
  },

  // --- CREATIVE (Photo) ---
  {
    id: 'draw_1',
    type: 'photo',
    needType: 'creative',
    title: 'Нарисуй дракона',
    description: 'Нарисуй своего Дракошу! Он хочет посмотреть, каким ты его видишь.',
    instruction: 'Возьми лист бумаги и карандаши, нарисуй дракона и сфотографируй рисунок',
    xpReward: 40,
    photoPrompt: 'рисунок дракона или динозавра, нарисованный ребёнком на бумаге',
  },
  {
    id: 'draw_2',
    type: 'photo',
    needType: 'creative',
    title: 'Нарисуй дом мечты',
    description: 'Дракоша хочет новый домик! Нарисуй дом своей мечты.',
    instruction: 'Нарисуй дом мечты — с башнями, садом или бассейном! Потом сфотографируй.',
    xpReward: 40,
    photoPrompt: 'рисунок дома или здания, нарисованный ребёнком',
  },
  {
    id: 'craft_1',
    type: 'photo',
    needType: 'creative',
    title: 'Сделай поделку из бумаги',
    description: 'Дракоша любит оригами! Сложи что-нибудь из бумаги.',
    instruction: 'Сложи самолётик, кораблик или звезду из бумаги и сфотографируй',
    xpReward: 45,
    photoPrompt: 'бумажная поделка: самолётик, кораблик, оригами или другая поделка из бумаги',
  },
  {
    id: 'photo_quest_1',
    type: 'photo',
    needType: 'creative',
    title: 'Фотоквест: найди красное',
    description: 'Дракоша потерял красный предмет! Найди что-нибудь красное дома.',
    instruction: 'Найди любой красный предмет дома и сфотографируй его',
    xpReward: 35,
    photoPrompt: 'красный предмет любого вида — игрушка, предмет одежды, фрукт или что-то другое красного цвета',
  },
  {
    id: 'photo_quest_2',
    type: 'photo',
    needType: 'creative',
    title: 'Фотоквест: найди круглое',
    description: 'Дракоша учит формы! Найди что-нибудь круглое.',
    instruction: 'Найди любой круглый предмет и сфотографируй его',
    xpReward: 35,
    photoPrompt: 'круглый предмет — мяч, тарелка, монета, яблоко или что-то другое круглой формы',
  },
  {
    id: 'draw_3',
    type: 'photo',
    needType: 'creative',
    title: 'Нарисуй семью',
    description: 'Дракоша хочет познакомиться с твоей семьёй! Нарисуй их.',
    instruction: 'Нарисуй себя и свою семью, потом сфотографируй рисунок',
    xpReward: 40,
    photoPrompt: 'детский рисунок людей или семьи',
  },

  // --- ENERGY (Activity) ---
  {
    id: 'jump_1',
    type: 'activity',
    needType: 'energy',
    title: 'Попрыгай 20 раз',
    description: 'Дракоша хочет зарядиться энергией! Попрыгай вместе с ним.',
    instruction: 'Прыгай на месте 20 раз — высоко, как кенгуру! Потом нажми "Готово"',
    xpReward: 25,
    duration: 40,
  },
  {
    id: 'dance_1',
    type: 'activity',
    needType: 'energy',
    title: 'Потанцуй 1 минуту',
    description: 'Дракоша хочет на дискотеку! Потанцуй под любимую музыку.',
    instruction: 'Включи музыку и танцуй 1 минуту — двигай руками и ногами!',
    xpReward: 30,
    duration: 60,
  },
  {
    id: 'stretch_1',
    type: 'activity',
    needType: 'energy',
    title: 'Сделай зарядку',
    description: 'Дракоша делает утреннюю зарядку! Присоединяйся.',
    instruction: 'Потянись вверх, повернись вправо и влево, присядь 5 раз. Готово!',
    xpReward: 25,
    duration: 45,
  },
  {
    id: 'run_1',
    type: 'activity',
    needType: 'energy',
    title: 'Пробеги по комнате',
    description: 'Дракоша хочет посоревноваться! Пробеги по комнате 5 раз.',
    instruction: 'Пробеги из угла в угол комнаты 5 раз — быстро!',
    xpReward: 25,
    duration: 45,
  },
  {
    id: 'clap_1',
    type: 'activity',
    needType: 'energy',
    title: 'Хлопай и топай',
    description: 'Дракоша любит ритм! Повтори его движения.',
    instruction: 'Хлопни 3 раза в ладоши, топни 3 раза ногами. Повтори 5 раз!',
    xpReward: 20,
    duration: 30,
  },
  {
    id: 'balance_1',
    type: 'activity',
    needType: 'energy',
    title: 'Постой на одной ноге',
    description: 'Дракоша тренирует баланс! Ты тоже сможешь!',
    instruction: 'Постой на одной ноге 15 секунд, потом на другой 15 секунд!',
    xpReward: 20,
    duration: 35,
  },
  {
    id: 'read_7',
    type: 'reading',
    needType: 'learning',
    title: 'Письмо из леса',
    description: 'Дракоша нашёл письмо в бутылке и хочет его прочитать.',
    instruction: 'Читай письмо вслух, как настоящий исследователь!',
    xpReward: 35,
    readingText: 'В лесу на мху лежало письмо. В нём было написано: "Спасибо тебе за доброту. Когда кто-то помогает другому, в мире становится светлее."',
  },
  {
    id: 'read_8',
    type: 'story',
    needType: 'learning',
    ageGroups: ['6-8', '9-11'],
    title: 'История про карту',
    description: 'Прочитай начало приключения и придумай продолжение.',
    instruction: 'Прочитай вслух и потом расскажи, чем закончилась история.',
    xpReward: 40,
    readingText: 'Однажды Дракоша нашёл старую карту с одним-единственным словом: "Дом". Он посмотрел по сторонам и понял, что путь домой начинается с первого шага...',
  },
  {
    id: 'quiz_math_3',
    type: 'quiz',
    needType: 'learning',
    ageGroups: ['6-8'],
    title: 'Фрукты на ладошке',
    description: 'Посчитай фруктовый счёт.',
    instruction: 'Выбери правильный ответ',
    xpReward: 35,
    quizQuestion: 'У тебя было 5 яблок, потом добавили ещё 2. Сколько стало?',
    quizOptions: ['6', '7', '8', '9'],
    quizAnswerIndex: 1,
    quizHint: 'Посчитай: 5 + 2.',
  },
  {
    id: 'quiz_logic_3',
    type: 'quiz',
    needType: 'learning',
    ageGroups: ['9-11'],
    title: 'Следующее число',
    description: 'Найди закономерность в ряду.',
    instruction: 'Посмотри, как меняются числа',
    xpReward: 45,
    quizQuestion: 'Какое число будет дальше: 3, 6, 12, 24, ?',
    quizOptions: ['30', '36', '48', '60'],
    quizAnswerIndex: 2,
    quizHint: 'Каждое число удваивается.',
  },
  {
    id: 'draw_4',
    type: 'photo',
    needType: 'creative',
    title: 'Нарисуй любимую игрушку',
    description: 'Дракоша хочет увидеть твою самую любимую игрушку.',
    instruction: 'Нарисуй игрушку и сфотографируй рисунок.',
    xpReward: 40,
    photoPrompt: 'детский рисунок любимой игрушки на бумаге',
  },
  {
    id: 'photo_quest_3',
    type: 'photo',
    needType: 'creative',
    title: 'Фотоквест: найди синее',
    description: 'Поймай в кадр что-нибудь синее.',
    instruction: 'Найди синий предмет дома и сфотографируй его.',
    xpReward: 35,
    photoPrompt: 'синий предмет любого вида',
  },
  {
    id: 'photo_quest_4',
    type: 'photo',
    needType: 'creative',
    title: 'Фотоквест: найди узор',
    description: 'Поищи вокруг интересный узор или текстуру.',
    instruction: 'Сфотографируй что-нибудь с красивым узором.',
    xpReward: 35,
    photoPrompt: 'предмет с заметным узором, полосками, клеткой или рельефом',
  },
  {
    id: 'craft_2',
    type: 'photo',
    needType: 'creative',
    title: 'Сделай бумажную корону',
    description: 'Дракоша хочет увидеть твою королевскую поделку.',
    instruction: 'Сложи корону, укрась её и сфотографируй.',
    xpReward: 45,
    photoPrompt: 'бумажная корона, сделанная ребёнком',
  },
  {
    id: 'jump_2',
    type: 'activity',
    needType: 'energy',
    title: 'Прыжки по островкам',
    description: 'Перепрыгни невидимые островки, как в приключении.',
    instruction: 'Сделай 10 лёгких прыжков на месте.',
    xpReward: 25,
    duration: 35,
  },
  {
    id: 'dance_2',
    type: 'activity',
    needType: 'energy',
    title: 'Танец зверят',
    description: 'Повтори движения Дракоши под музыку.',
    instruction: 'Танцуй 1 минуту: руки, плечи, шаги и улыбка.',
    xpReward: 30,
    duration: 60,
  },
  {
    id: 'stretch_2',
    type: 'activity',
    needType: 'energy',
    title: 'Кошка и собака',
    description: 'Мягкая разминка для спины и плеч.',
    instruction: 'Сделай позу кошки и позу собаки по 3 раза.',
    xpReward: 25,
    duration: 40,
  },
  {
    id: 'run_2',
    type: 'activity',
    needType: 'energy',
    title: 'Быстрые шаги',
    description: 'Дракоша хочет быстрый спринт на месте.',
    instruction: 'Пробеги на месте 30 секунд, потом спокойно вдохни.',
    xpReward: 25,
    duration: 30,
  },
  {
    id: 'clap_2',
    type: 'activity',
    needType: 'energy',
    title: 'Ритм ладошек',
    description: 'Поймай ритм и повтори за Дракошей.',
    instruction: 'Сделай 5 раундов хлопков и лёгких топов.',
    xpReward: 20,
    duration: 30,
  },
  {
    id: 'balance_2',
    type: 'activity',
    needType: 'energy',
    title: 'Линия равновесия',
    description: 'Представь, что идёшь по узкой тропинке.',
    instruction: 'Пройди по воображаемой линии 20 шагов медленно и ровно.',
    xpReward: 20,
    duration: 35,
  },
  {
    id: 'read_9',
    type: 'reading',
    needType: 'learning',
    title: 'Секрет лунного света',
    description: 'Дракоша хочет узнать, почему Луна светится.',
    instruction: 'Прочитай текст как маленький исследователь.',
    xpReward: 35,
    readingText: 'Луна не светит сама. Она отражает свет Солнца, как большой серебряный зеркальный шар. Поэтому ночью она кажется яркой и волшебной.',
  },
  {
    id: 'read_10',
    type: 'story',
    needType: 'learning',
    ageGroups: ['6-8', '9-11'],
    title: 'История про доброго робота',
    description: 'Прочитай начало и придумай, что робот сделал дальше.',
    instruction: 'Читай вслух и потом продолжи историю своими словами.',
    xpReward: 40,
    readingText: 'В мастерской появился маленький робот. Он умел только одно: находить потерянные вещи. Но однажды он нашёл не ключи, а чью-то грустную улыбку...',
  },
  {
    id: 'quiz_math_4',
    type: 'quiz',
    needType: 'learning',
    ageGroups: ['6-8'],
    title: 'Сколько лап?',
    description: 'Счёт на простом и понятном примере.',
    instruction: 'Выбери правильный ответ',
    xpReward: 35,
    quizQuestion: 'У двух котят всего сколько лап?',
    quizOptions: ['6', '8', '10', '12'],
    quizAnswerIndex: 1,
    quizHint: 'У одного котёнка 4 лапы.',
  },
  {
    id: 'quiz_logic_4',
    type: 'quiz',
    needType: 'learning',
    ageGroups: ['9-11'],
    title: 'Шифр цвета',
    description: 'Найди следующее звено в цветовой логике.',
    instruction: 'Смотри на повторяющийся порядок',
    xpReward: 45,
    quizQuestion: 'Какой цвет следующий: красный, синий, красный, синий, ?',
    quizOptions: ['Зелёный', 'Жёлтый', 'Красный', 'Синий'],
    quizAnswerIndex: 2,
    quizHint: 'Порядок повторяется.',
  },
  {
    id: 'draw_5',
    type: 'photo',
    needType: 'creative',
    title: 'Нарисуй свой маршрут',
    description: 'Покажи дорогу от дома до любимого места.',
    instruction: 'Нарисуй простой маршрут и сфотографируй рисунок.',
    xpReward: 40,
    photoPrompt: 'детский рисунок маршрута или карты',
  },
  {
    id: 'photo_quest_5',
    type: 'photo',
    needType: 'creative',
    title: 'Фотоквест: найди мягкое',
    description: 'Поймай в кадр что-то пушистое или мягкое.',
    instruction: 'Найди мягкий предмет и сфотографируй его.',
    xpReward: 35,
    photoPrompt: 'мягкий предмет, ткань, игрушка, плед или подушка',
  },
  {
    id: 'craft_3',
    type: 'photo',
    needType: 'creative',
    title: 'Сделай маску героя',
    description: 'Дракоша хочет примерить маску приключений.',
    instruction: 'Сделай маску из бумаги, укрась её и сфотографируй.',
    xpReward: 45,
    photoPrompt: 'бумажная маска героя, животного или фантастического персонажа',
  },
  {
    id: 'jump_3',
    type: 'activity',
    needType: 'energy',
    title: 'Пружинки',
    description: 'Мягкие и быстрые прыжки для разогрева.',
    instruction: 'Сделай 15 маленьких пружинистых прыжков.',
    xpReward: 25,
    duration: 30,
  },
  {
    id: 'dance_3',
    type: 'activity',
    needType: 'energy',
    title: 'Танец плечами',
    description: 'Разминка с музыкой без лишнего шума.',
    instruction: 'Под музыку покрути плечами, руками и сделай шаги в стороны.',
    xpReward: 30,
    duration: 45,
  },
  {
    id: 'stretch_3',
    type: 'activity',
    needType: 'energy',
    title: 'Вверх и вниз',
    description: 'Короткая разминка для всего тела.',
    instruction: 'Потянись вверх, наклонись вниз и повтори 5 раз.',
    xpReward: 25,
    duration: 35,
  },
  {
    id: 'run_3',
    type: 'activity',
    needType: 'energy',
    title: 'Тихий бег',
    description: 'Немного движения, чтобы проснуться.',
    instruction: 'Пробеги на месте 20 секунд, потом спокойно подыши.',
    xpReward: 20,
    duration: 25,
  },
];

export function getQuestsByNeed(needType: string): Quest[] {
  return ALL_QUESTS.filter(q => q.needType === needType);
}

function isAgeCompatible(quest: Quest, ageGroup?: AgeGroup): boolean {
  return !ageGroup || !quest.ageGroups || quest.ageGroups.includes(ageGroup);
}

function getAvailableQuests(needType: string, excludeIds: string[] = [], ageGroup?: AgeGroup): Quest[] {
  return ALL_QUESTS.filter(
    q => q.needType === needType && !excludeIds.includes(q.id) && isAgeCompatible(q, ageGroup)
  );
}

export function getRandomQuest(needType: string, excludeIds: string[] = [], ageGroup?: AgeGroup): Quest {
  const available = getAvailableQuests(needType, excludeIds, ageGroup);
  if (available.length === 0) return ALL_QUESTS.filter(q => q.needType === needType)[0];
  return available[Math.floor(Math.random() * available.length)];
}

export function getDailyQuest(ageGroup: AgeGroup, dayKey: string): Quest | undefined {
  const available = ALL_QUESTS.filter(q => isAgeCompatible(q, ageGroup));
  if (!available.length) return undefined;

  let hash = 0;
  for (const char of `${ageGroup}:${dayKey}`) {
    hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  }

  return available[hash % available.length];
}

export function getQuestsByNeedForAge(needType: string, ageGroup: AgeGroup): Quest[] {
  return ALL_QUESTS.filter(q => q.needType === needType && isAgeCompatible(q, ageGroup));
}
